create table CUSTOMER_TABLE(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL
);

create table ACCOUNT_TABLE(
    ID INTEGER NOT NULL PRIMARY KEY,
    OWNER BIGINT NOT NULL,
    ACCOUNT_NUMBER BIGINT NOT NULL,
    BALANCE DECIMAL NOT NULL,
    NAME VARCHAR(256) NOT NULL
);

create table TRANSACTION_TABLE(
    ID INTEGER NOT NULL PRIMARY KEY,
    TO_ACOUNT_NUMBER BIGINT NOT NULL,
    FROM_ACOUNT_NUMBER BIGINT NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    NAME VARCHAR(256) NOT NULL
);


